import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid place-content-center`}>
        <div className="min-[480px]:max-w-[480px] min-h-full overflow-x-hidden mx-0 my-0 py-0 bg-white relative shadow-[0_0_20px_rgba(0,0,0,0.05)]">
          {children}
        </div>
      </body>
    </html>
  )
}
